### ISSUE TITLE
[2024-07-06] SwanGBA v0.6.4 has no audio output

### ISSUE THREAD

**Issue by OmDRetro** [FluBBaOfWard/SwanGBA#1]
Built SwanGBA v0.6.4 with the ff.:

* WSRTC V0.2.1
* WSEEPROM V0.7.0
* Sphinx V0.3.6
    * `WSAudio.s`: I replaced line 171 with `ldr r1,=vol1_L` in order to build and test this.
* ARMv30MZ V0.8.9

"UAT" was done on NanoBoyAdvance v 1.8.1

***

### Observation(s):
* No audio output no matter the mode change(headphone mode and audio level switching by pressing `select`), but the emulator does run significantly faster than SwanAdvance.
    * It made no difference if I used the emulator on an NDS or the GBA. The behavior is the same

**Comment by OmDRetro** [comment]
Hey Flubba,

If you need me to conduct certain tests, I think I'll be able to lend you a hand here since ROM builders aren't required on my end as I already implemented this on the [pre-release kernel of SCFW](https://gbatemp.net/threads/scfw-bleeding-edge-modular-kernel-branch.656629/) (Custom kernel/firmware for the SuperCard SD). Someone already used this and left the ff. [observation](https://gbatemp.net/threads/scfw-bleeding-edge-modular-kernel-branch.656629/post-10452938):

```
Wow, Wonderswan! It's impressive to see that running. Despite the slowdown on many games (RIP every Digimon game) the Final Fantasy ports seem very playable, which I love to see. These games really suit the GBA screen.

I did struggle to get a working save file though. I can save, return to the title screen, and load, but as soon as I reset or exit out, it's gone. Even if I dump the SRAM to a .sav and load it before booting up the game/emulator, I'm getting nothing.
Save/Load states don't seem functional either.
```

The above indicates that maybe SRAM saves aren't intended to be functional yet.

**Comment by FluBBaOfWard** [comment]
Please create a separate issue for the SRAM and I will take a look at it.

**Comment by OmDRetro** [comment]
> Please create a separate issue for the SRAM and I will take a look at it.

This is done. Thanks a lot for checking, Flubba

**Comment by FluBBaOfWard** [comment]
This is done.
