### ISSUE TITLE
There is no release, it doesn’t exist

### ISSUE THREAD

**Issue by ChimpWithPhone** [FluBBaOfWard/SwanGBA#2]
Was excited to try this but then realised there’s no release, why is this?

**Comment by FluBBaOfWard** [comment]
Because there is no builder... so it's pretty useless for most people anyway.
If you're really interested I can put up a build when I do the next release for DS.

**Comment by ChimpWithPhone** [comment]
Yes I’m definitely interested! I did find it online, got as far as the loading screen on an emulator before seeing a black screen, I could open the menus also using L+R but games wouldn’t work. Can you make a build that also works on emulators? Thankyou for your work so far.
![IMG_8672](https://github.com/user-attachments/assets/ec987bd3-e24e-432b-9176-2c6fb1333991)
![IMG_8662](https://github.com/user-attachments/assets/a5d9b053-b861-4148-82d7-6215e767ccbb)

**Comment by FluBBaOfWard** [comment]
I... I don't even... SwanAdvance is not SwanGBA, it's not been touched for years, compatibility is not great.
Isn't there a WonderSwan emulator for your platform so you have to use a GBA one? Can't you run a DS emulator instead?

**Comment by ChimpWithPhone** [comment]
I’m running it on ArcEmu for my Apple Watch so only gba, if you finish SwanGBA let me know I’d love to test it for you

**Comment by FluBBaOfWard** [comment]
I will fix a hacked version of the old SwanAdvance.

**Comment by ChimpWithPhone** [comment]
That would be great if you can!! Hopefully it can work on emulators aswell

**Comment by FluBBaOfWard** [comment]
It works on all emulators I've tested on (mGBA, NanoBoyAdvance, No$GBA), NitroSwan works on all DS emulators I've tested it on (DeSmuME, melonDS, No$GBA).

**Comment by ChimpWithPhone** [comment]
That’s great!! Please let me know when it’s finished :)

**Comment by FluBBaOfWard** [comment]
That has always been the case, it's nothing new.

**Comment by ChimpWithPhone** [comment]
Always been the case? Then why won’t it work on Delta or ArcEmu emulators for iOS?

**Comment by FluBBaOfWard** [comment]
How would I know? The emulator works on real HW and on the emulators I can test with. I can't debug everyone else's emulators as well as my own.

**Comment by ChimpWithPhone** [comment]
You insinuated that it works on all emulators mate

**Comment by FluBBaOfWard** [comment]
No, you insinuated that it doesn't work on any emulators...

**Comment by ChimpWithPhone** [comment]
I assumed it didn’t as it doesn’t work on the 2 emulators I tried..

**Comment by FluBBaOfWard** [comment]
https://github.com/FluBBaOfWard/SwanGBA/releases/tag/v0.6.6

**Comment by ChimpWithPhone** [comment]
Amazing work, works perfectly!
