### ISSUE TITLE
SwanGBA v0.6.4 - Unable to save to SRAM

### ISSUE THREAD

**Issue by OmDRetro** [FluBBaOfWard/SwanGBA#3]
## Marking the SRAM issue here for documentation

This issue was first mentioned on a [GBA Temp post](https://gbatemp.net/threads/scfw-bleeding-edge-modular-kernel-branch.656629/post-10452938)

Excerpt from GBATemp:
```
Wow, Wonderswan! It's impressive to see that running. Despite the slowdown on many games (RIP every Digimon game) the Final Fantasy ports seem very playable, which I love to see. These games really suit the GBA screen.

I did struggle to get a working save file though. I can save, return to the title screen, and load, but as soon as I reset or exit out, it's gone. Even if I dump the SRAM to a .sav and load it before booting up the game/emulator, I'm getting nothing.
Save/Load states don't seem functional either.
```

### UAT was done on a GBA with a SuperCard SD flashcart running SCFW

**Comment by FluBBaOfWard** [comment]
WonderSwan NVRAM should now be copied to/from GBA SRAM when using the menu items Load/Save-NVRAM.
